# Generated by Django 3.2.6 on 2021-09-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feestype', models.CharField(default='', max_length=120)),
                ('class_fees', models.CharField(default='', max_length=120)),
                ('fees_value', models.CharField(default='', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('admno', models.CharField(max_length=120, primary_key='True', serialize=False)),
                ('roll', models.CharField(default='', max_length=5)),
                ('class_student', models.CharField(default='', max_length=2)),
                ('section', models.CharField(default='', max_length=1)),
                ('fname', models.CharField(default='', max_length=30)),
                ('lname', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=6)),
                ('category', models.CharField(default='', max_length=120)),
                ('religion', models.CharField(default='', max_length=50)),
                ('caste', models.CharField(default='', max_length=35)),
                ('phno', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=50)),
                ('fathername', models.CharField(default='', max_length=120)),
                ('fatherphone', models.CharField(default='', max_length=10)),
                ('motherphone', models.CharField(default='', max_length=10)),
                ('mothername', models.CharField(default='', max_length=120)),
                ('fatherocc', models.CharField(default='', max_length=120)),
                ('motherocc', models.CharField(default='', max_length=120)),
                ('guardianphone', models.CharField(default='', max_length=10)),
                ('guardianname', models.CharField(default='', max_length=120)),
                ('guardianemail', models.CharField(default='', max_length=120)),
                ('guardianrelation', models.CharField(default='', max_length=30)),
                ('guardianocc', models.CharField(default='', max_length=120)),
                ('guardianadd', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
